//A blacklist that removes all secondary weapons and all weapon/respawn/special backpacks
blacklist1 = [
	"launch_NLAW_F",
	"launch_RPG32_F",
	"launch_Titan_base",
	"launch_Titan_short_base",
	"launch_B_Titan_F",
	"launch_I_Titan_F",
	"launch_O_Titan_F",
	"launch_Titan_F",
	"launch_B_Titan_short_F",
	"launch_I_Titan_short_F",
	"launch_O_Titan_short_F",
	"launch_Titan_short_F",
	"launch_RPG32_ghex_F",
	"launch_RPG7_F",
	"launch_B_Titan_tna_F",
	"launch_B_Titan_short_tna_F",
	"launch_O_Titan_ghex_F",
	"launch_O_Titan_short_ghex_F",
	"optic_Arco",
	"optic_Hamr",
	"optic_Aco",
	"optic_ACO_grn",
	"optic_Aco_smg",
	"optic_ACO_grn_smg",
	"optic_Holosight",
	"optic_Holosight_smg",
	"optic_SOS",
	"optic_MRCO",
	"optic_NVS",
	"optic_Nightstalker",
	"optic_tws",
	"optic_tws_mg",
	"optic_DMS",
	"optic_Yorris",
	"optic_MRD",
	"optic_LRPS",
	"optic_AMS_base",
	"optic_AMS",
	"optic_AMS_khk",
	"optic_AMS_snd",
	"optic_KHS_base",
	"optic_KHS_blk",
	"optic_KHS_hex",
	"optic_KHS_old",
	"optic_KHS_tan",
	"optic_Arco_blk_F",
	"optic_Arco_ghex_F",
	"optic_DMS_ghex_F",
	"optic_Hamr_khk_F",
	"optic_ERCO_blk_F",
	"optic_ERCO_khk_F",
	"optic_ERCO_snd_F",
	"optic_SOS_khk_F",
	"optic_LRPS_tna_F",
	"optic_LRPS_ghex_F",
	"optic_Holosight_blk_F",
	"optic_Holosight_khk_F",
	"optic_Holosight_smg_blk_F"
];

//["optic_Nightstalker","optic_KHS_blk","optic_KHS_tan","optic_KHS_hex","optic_Arco","optic_ACO_grn_smg","optic_Hamr_khk_F","optic_SOS_khk_F","optic_Arco_ghex_F","optic_Arco_blk_F","optic_DMS_ghex_F","optic_ERCO_blk_F","optic_ERCO_khk_F","optic_ERCO_snd_F","optic_LRPS_ghex_F","optic_LRPS_tna_F","optic_Holosight_blk_F","optic_Holosight_khk_F","optic_Holosight_smg_blk_F"]
if !( isServer ) exitWith {};

_ammoBox = _this;

//[ box, [ white, black ], targets, name, condition ]
JIPID =  [ _ammoBox, [west, "blacklist1"], 0, "No launchers/optics", { true } ] call LARs_fnc_blacklistArsenal;